import {CategoryWithCards} from "./interfaces";
export const uploadPath = {
  cloudinaryImg: "https://res.cloudinary.com/dehcs7uhk/image/upload/",
  cloudinaryAudio: "https://res.cloudinary.com/dehcs7uhk/video/upload/",
};
export const typesForFoleder = [
  {type: "image", folder: "img"},
  {type: "audio", folder: "audio"},
  {type: "video", folder: "video"},
];

export const CARDS: Array<CategoryWithCards> = [
  {
    category: {id: 1, name: "Emotions", image: "img/happy.jpg"},
    cards: [
      {
        id: 1,
        word: "sad",
        translation: "грустный",
        image: "img/sad.jpg",
        audioSrc: "audio/sad.mp3",
      },
      {
        id: 2,
        word: "angry",
        translation: "сердитый",
        image: "img/angry.jpg",
        audioSrc: "audio/angry.mp3",
      },
      {
        id: 3,
        word: "happy",
        translation: "счастливый",
        image: "img/happy.jpg",
        audioSrc: "audio/happy.mp3",
      },
      {
        id: 4,
        word: "tired",
        translation: "уставший",
        image: "img/tired.jpg",
        audioSrc: "audio/tired.mp3",
      },
      {
        id: 5,
        word: "surprised",
        translation: "удивлённый",
        image: "img/surprised.jpg",
        audioSrc: "audio/surprised.mp3",
      },
      {
        id: 6,
        word: "scared",
        translation: "испуганный",
        image: "img/scared.jpg",
        audioSrc: "audio/scared.mp3",
      },
      {
        id: 7,
        word: "smile",
        translation: "улыбка",
        image: "img/smile.jpg",
        audioSrc: "audio/smile.mp3",
      },
      {
        id: 8,
        word: "laugh",
        translation: "смех",
        image: "img/laugh.jpg",
        audioSrc: "audio/laugh.mp3",
      },
    ],
  },
  {
    category: {id: 2, name: "Clothes", image: "img/dress.jpg"},
    cards: [
      {
        id: 9,
        word: "skirt",
        translation: "юбка",
        image: "img/skirt.jpg",
        audioSrc: "audio/skirt.mp3",
      },
      {
        id: 10,
        word: "pants",
        translation: "брюки",
        image: "img/pants.jpg",
        audioSrc: "audio/pants.mp3",
      },
      {
        id: 11,
        word: "blouse",
        translation: "блузка",
        image: "img/blouse.jpg",
        audioSrc: "audio/blouse.mp3",
      },
      {
        id: 12,
        word: "dress",
        translation: "платье",
        image: "img/dress.jpg",
        audioSrc: "audio/dress.mp3",
      },
      {
        id: 13,
        word: "boot",
        translation: "ботинок",
        image: "img/boot.jpg",
        audioSrc: "audio/boot.mp3",
      },
      {
        id: 14,
        word: "shirt",
        translation: "рубашка",
        image: "img/shirt.jpg",
        audioSrc: "audio/shirt.mp3",
      },
      {
        id: 15,
        word: "coat",
        translation: "пальто",
        image: "img/coat.jpg",
        audioSrc: "audio/coat.mp3",
      },
      {
        id: 16,
        word: "shoe",
        translation: "туфли",
        image: "img/shoe.jpg",
        audioSrc: "audio/shoe.mp3",
      },
    ],
  },
  {
    category: {id: 3, name: "Animal (set A)", image: "img/fish1.jpg"},
    cards: [
      {
        id: 17,
        word: "bird",
        translation: "птица",
        image: "img/bird.jpg",
        audioSrc: "audio/bird.mp3",
      },
      {
        id: 18,
        word: "fish",
        translation: "рыба",
        image: "img/fish1.jpg",
        audioSrc: "audio/fish.mp3",
      },
      {
        id: 19,
        word: "frog",
        translation: "жаба",
        image: "img/frog.jpg",
        audioSrc: "audio/frog.mp3",
      },
      {
        id: 20,
        word: "giraffe",
        translation: "жирафа",
        image: "img/giraffe.jpg",
        audioSrc: "audio/giraffe.mp3",
      },
      {
        id: 21,
        word: "lion",
        translation: "лев",
        image: "img/lion.jpg",
        audioSrc: "audio/lion.mp3",
      },
      {
        id: 22,
        word: "mouse",
        translation: "мышь",
        image: "img/mouse.jpg",
        audioSrc: "audio/mouse.mp3",
      },
      {
        id: 23,
        word: "turtle",
        translation: "черепаха",
        image: "img/turtle.jpg",
        audioSrc: "audio/turtle.mp3",
      },
      {
        id: 24,
        word: "dolphin",
        translation: "дельфин",
        image: "img/dolphin.jpg",
        audioSrc: "audio/dolphin.mp3",
      },
    ],
  },
  {
    category: {id: 4, name: "Animal (set B)", image: "img/cat.jpg"},
    cards: [
      {
        id: 25,
        word: "cat",
        translation: "кот",
        image: "img/cat.jpg",
        audioSrc: "audio/cat.mp3",
      },
      {
        id: 26,
        word: "chick",
        translation: "цыплёнок",
        image: "img/chick.jpg",
        audioSrc: "audio/chick.mp3",
      },
      {
        id: 27,
        word: "chicken",
        translation: "курица",
        image: "img/chicken.jpg",
        audioSrc: "audio/chicken.mp3",
      },
      {
        id: 28,
        word: "dog",
        translation: "собака",
        image: "img/dog.jpg",
        audioSrc: "audio/dog.mp3",
      },
      {
        id: 29,
        word: "horse",
        translation: "лошадь",
        image: "img/horse.jpg",
        audioSrc: "audio/horse.mp3",
      },
      {
        id: 30,
        word: "pig",
        translation: "свинья",
        image: "img/pig.jpg",
        audioSrc: "audio/pig.mp3",
      },
      {
        id: 31,
        word: "rabbit",
        translation: "кролик",
        image: "img/rabbit.jpg",
        audioSrc: "audio/rabbit.mp3",
      },
      {
        id: 32,
        word: "sheep",
        translation: "овца",
        image: "img/sheep.jpg",
        audioSrc: "audio/sheep.mp3",
      },
    ],
  },
  {
    category: {id: 5, name: "Animal (set C)", image: "img/eagle.jpg"},
    cards: [
      {
        id: 33,
        word: "bat",
        translation: "летучая мышь",
        image: "img/bat.jpg",
        audioSrc: "audio/bat.mp3",
      },
      {
        id: 34,
        word: "eagle",
        translation: "орел",
        image: "img/eagle.jpg",
        audioSrc: "audio/eagle.mp3",
      },
      {
        id: 35,
        word: "goose",
        translation: "гусь",
        image: "img/goose.jpg",
        audioSrc: "audio/goose.mp3",
      },
      {
        id: 36,
        word: "parrot",
        translation: "попугай",
        image: "img/parrot.jpg",
        audioSrc: "audio/parrot.mp3",
      },
      {
        id: 37,
        word: "crow",
        translation: "ворона",
        image: "img/crow.jpg",
        audioSrc: "audio/crow.mp3",
      },
      {
        id: 38,
        word: "penguin",
        translation: "пенгвин",
        image: "img/penguin.jpg",
        audioSrc: "audio/penguin.mp3",
      },
      {
        id: 39,
        word: "owl",
        translation: "сова",
        image: "img/owl.jpg",
        audioSrc: "audio/owl.mp3",
      },
      {
        id: 40,
        word: "duck",
        translation: "утка",
        image: "img/duck.jpg",
        audioSrc: "audio/duck.mp3",
      },
    ],
  },
  {
    category: {id: 6, name: "Food", image: "img/apple.jpg"},
    cards: [
      {
        id: 41,
        word: "apple",
        translation: "яблоко",
        image: "img/apple.jpg",
        audioSrc: "audio/apple.mp3",
      },
      {
        id: 42,
        word: "tomato",
        translation: "помидор",
        image: "img/tomato.jpg",
        audioSrc: "audio/tomato.mp3",
      },
      {
        id: 43,
        word: "lemon",
        translation: "лемон",
        image: "img/lemon.jpg",
        audioSrc: "audio/lemon.mp3",
      },
      {
        id: 44,
        word: "orange",
        translation: "апельсин",
        image: "img/orange.jpg",
        audioSrc: "audio/orange.mp3",
      },
      {
        id: 45,
        word: "potato",
        translation: "картошка",
        image: "img/potato.jpg",
        audioSrc: "audio/potato.mp3",
      },
      {
        id: 46,
        word: "rice",
        translation: "рис",
        image: "img/rice.jpg",
        audioSrc: "audio/rice.mp3",
      },
      {
        id: 47,
        word: "cheese",
        translation: "сыр",
        image: "img/cheese.jpg",
        audioSrc: "audio/cheese.mp3",
      },
      {
        id: 48,
        word: "bread",
        translation: "хлеб",
        image: "img/bread.jpg",
        audioSrc: "audio/bread.mp3",
      },
    ],
  },
  {
    category: {id: 7, name: "Action (set A)", image: "img/play.jpg"},
    cards: [
      {
        id: 49,
        word: "open",
        translation: "открывать",
        image: "img/open.jpg",
        audioSrc: "audio/open.mp3",
      },
      {
        id: 50,
        word: "play",
        translation: "играть",
        image: "img/play.jpg",
        audioSrc: "audio/play.mp3",
      },
      {
        id: 51,
        word: "point",
        translation: "указывать",
        image: "img/point.jpg",
        audioSrc: "audio/point.mp3",
      },
      {
        id: 52,
        word: "ride",
        translation: "ездить",
        image: "img/ride.jpg",
        audioSrc: "audio/ride.mp3",
      },
      {
        id: 53,
        word: "run",
        translation: "бегать",
        image: "img/run.jpg",
        audioSrc: "audio/run.mp3",
      },
      {
        id: 54,
        word: "sing",
        translation: "петь",
        image: "img/sing.jpg",
        audioSrc: "audio/sing.mp3",
      },
      {
        id: 55,
        word: "skip",
        translation: "пропускать, прыгать",
        image: "img/skip.jpg",
        audioSrc: "audio/skip.mp3",
      },
      {
        id: 56,
        word: "swim",
        translation: "плавать",
        image: "img/swim.jpg",
        audioSrc: "audio/swim.mp3",
      },
    ],
  },
  {
    category: {id: 8, name: "Action (set B)", image: "img/dance.jpg"},
    cards: [
      {
        id: 57,
        word: "cry",
        translation: "плакать",
        image: "img/cry.jpg",
        audioSrc: "audio/cry.mp3",
      },
      {
        id: 58,
        word: "dance",
        translation: "танцевать",
        image: "img/dance.jpg",
        audioSrc: "audio/dance.mp3",
      },
      {
        id: 59,
        word: "dive",
        translation: "нырять",
        image: "img/dive.jpg",
        audioSrc: "audio/dive.mp3",
      },
      {
        id: 60,
        word: "draw",
        translation: "рисовать",
        image: "img/draw.jpg",
        audioSrc: "audio/draw.mp3",
      },
      {
        id: 61,
        word: "fly",
        translation: "летать",
        image: "img/fly.jpg",
        audioSrc: "audio/fly.mp3",
      },
      {
        id: 62,
        word: "hug",
        translation: "обнимать",
        image: "img/hug.jpg",
        audioSrc: "audio/hug.mp3",
      },
      {
        id: 63,
        word: "jump",
        translation: "прыгать",
        image: "img/jump.jpg",
        audioSrc: "audio/jump.mp3",
      },
      {
        id: 64,
        word: "fish",
        translation: "рыбачить",
        image: "img/fish.jpg",
        audioSrc: "audio/fish.mp3",
      },
    ],
  },
];
